//
// File generated by rootcint at Fri Sep 19 17:08:06 2014

// Do NOT change. Changes will be lost next time file is generated
//

#define R__DICTIONARY_FILENAME dOdIincludedIDictionary_DmpEvtFdigiBgo
#include "RConfig.h" //rootcint 4834
#if !defined(R__ACCESS_IN_SYMBOL)
//Break the privacy of classes -- Disabled for the moment
#define private public
#define protected public
#endif

// Since CINT ignores the std namespace, we need to do so in this file.
namespace std {} using namespace std;
#include "Dictionary_DmpEvtFdigiBgo.h"

#include "TCollectionProxyInfo.h"
#include "TClass.h"
#include "TBuffer.h"
#include "TMemberInspector.h"
#include "TError.h"

#ifndef G__ROOT
#define G__ROOT
#endif

#include "RtypesImp.h"
#include "TIsAProxy.h"
#include "TFileMergeInfo.h"

// Direct notice to TROOT of the dictionary's loading.
namespace {
   static struct DictInit {
      DictInit() {
         ROOT::RegisterModule();
      }
   } __TheDictionaryInitializer;
}

// START OF SHADOWS

namespace ROOT {
   namespace Shadow {
   } // of namespace Shadow
} // of namespace ROOT
// END OF SHADOWS

namespace ROOT {
   void DmpEvtFdigiBgo_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void *new_DmpEvtFdigiBgo(void *p = 0);
   static void *newArray_DmpEvtFdigiBgo(Long_t size, void *p);
   static void delete_DmpEvtFdigiBgo(void *p);
   static void deleteArray_DmpEvtFdigiBgo(void *p);
   static void destruct_DmpEvtFdigiBgo(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const ::DmpEvtFdigiBgo*)
   {
      ::DmpEvtFdigiBgo *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TInstrumentedIsAProxy< ::DmpEvtFdigiBgo >(0);
      static ::ROOT::TGenericClassInfo 
         instance("DmpEvtFdigiBgo", ::DmpEvtFdigiBgo::Class_Version(), "./include/DmpEvtFdigiBgo.h", 13,
                  typeid(::DmpEvtFdigiBgo), DefineBehavior(ptr, ptr),
                  &::DmpEvtFdigiBgo::Dictionary, isa_proxy, 4,
                  sizeof(::DmpEvtFdigiBgo) );
      instance.SetNew(&new_DmpEvtFdigiBgo);
      instance.SetNewArray(&newArray_DmpEvtFdigiBgo);
      instance.SetDelete(&delete_DmpEvtFdigiBgo);
      instance.SetDeleteArray(&deleteArray_DmpEvtFdigiBgo);
      instance.SetDestructor(&destruct_DmpEvtFdigiBgo);
      return &instance;
   }
   TGenericClassInfo *GenerateInitInstance(const ::DmpEvtFdigiBgo*)
   {
      return GenerateInitInstanceLocal((::DmpEvtFdigiBgo*)0);
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const ::DmpEvtFdigiBgo*)0x0); R__UseDummy(_R__UNIQUE_(Init));
} // end of namespace ROOT

//______________________________________________________________________________
TClass *DmpEvtFdigiBgo::fgIsA = 0;  // static to hold class pointer

//______________________________________________________________________________
const char *DmpEvtFdigiBgo::Class_Name()
{
   return "DmpEvtFdigiBgo";
}

//______________________________________________________________________________
const char *DmpEvtFdigiBgo::ImplFileName()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtFdigiBgo*)0x0)->GetImplFileName();
}

//______________________________________________________________________________
int DmpEvtFdigiBgo::ImplFileLine()
{
   return ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtFdigiBgo*)0x0)->GetImplFileLine();
}

//______________________________________________________________________________
void DmpEvtFdigiBgo::Dictionary()
{
   fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtFdigiBgo*)0x0)->GetClass();
}

//______________________________________________________________________________
TClass *DmpEvtFdigiBgo::Class()
{
   if (!fgIsA) fgIsA = ::ROOT::GenerateInitInstanceLocal((const ::DmpEvtFdigiBgo*)0x0)->GetClass();
   return fgIsA;
}

//______________________________________________________________________________
void DmpEvtFdigiBgo::Streamer(TBuffer &R__b)
{
   // Stream an object of class DmpEvtFdigiBgo.

   if (R__b.IsReading()) {
      R__b.ReadClassBuffer(DmpEvtFdigiBgo::Class(),this);
   } else {
      R__b.WriteClassBuffer(DmpEvtFdigiBgo::Class(),this);
   }
}

//______________________________________________________________________________
void DmpEvtFdigiBgo::ShowMembers(TMemberInspector &R__insp)
{
      // Inspect the data members of an object of class DmpEvtFdigiBgo.
      TClass *R__cl = ::DmpEvtFdigiBgo::IsA();
      if (R__cl || R__insp.IsA()) { }
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fGlobalPmtID", (void*)&fGlobalPmtID);
      R__insp.InspectMember("vector<short>", (void*)&fGlobalPmtID, "fGlobalPmtID.", false);
      R__insp.Inspect(R__cl, R__insp.GetParent(), "fADC", (void*)&fADC);
      R__insp.InspectMember("vector<short>", (void*)&fADC, "fADC.", false);
      TObject::ShowMembers(R__insp);
}

namespace ROOT {
   // Wrappers around operator new
   static void *new_DmpEvtFdigiBgo(void *p) {
      return  p ? new(p) ::DmpEvtFdigiBgo : new ::DmpEvtFdigiBgo;
   }
   static void *newArray_DmpEvtFdigiBgo(Long_t nElements, void *p) {
      return p ? new(p) ::DmpEvtFdigiBgo[nElements] : new ::DmpEvtFdigiBgo[nElements];
   }
   // Wrapper around operator delete
   static void delete_DmpEvtFdigiBgo(void *p) {
      delete ((::DmpEvtFdigiBgo*)p);
   }
   static void deleteArray_DmpEvtFdigiBgo(void *p) {
      delete [] ((::DmpEvtFdigiBgo*)p);
   }
   static void destruct_DmpEvtFdigiBgo(void *p) {
      typedef ::DmpEvtFdigiBgo current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class ::DmpEvtFdigiBgo

namespace ROOT {
   void vectorlEshortgR_ShowMembers(void *obj, TMemberInspector &R__insp);
   static void vectorlEshortgR_Dictionary();
   static void *new_vectorlEshortgR(void *p = 0);
   static void *newArray_vectorlEshortgR(Long_t size, void *p);
   static void delete_vectorlEshortgR(void *p);
   static void deleteArray_vectorlEshortgR(void *p);
   static void destruct_vectorlEshortgR(void *p);

   // Function generating the singleton type initializer
   static TGenericClassInfo *GenerateInitInstanceLocal(const vector<short>*)
   {
      vector<short> *ptr = 0;
      static ::TVirtualIsAProxy* isa_proxy = new ::TIsAProxy(typeid(vector<short>),0);
      static ::ROOT::TGenericClassInfo 
         instance("vector<short>", -2, "vector.dll", 0,
                  typeid(vector<short>), DefineBehavior(ptr, ptr),
                  0, &vectorlEshortgR_Dictionary, isa_proxy, 0,
                  sizeof(vector<short>) );
      instance.SetNew(&new_vectorlEshortgR);
      instance.SetNewArray(&newArray_vectorlEshortgR);
      instance.SetDelete(&delete_vectorlEshortgR);
      instance.SetDeleteArray(&deleteArray_vectorlEshortgR);
      instance.SetDestructor(&destruct_vectorlEshortgR);
      instance.AdoptCollectionProxyInfo(TCollectionProxyInfo::Generate(TCollectionProxyInfo::Pushback< vector<short> >()));
      return &instance;
   }
   // Static variable to force the class initialization
   static ::ROOT::TGenericClassInfo *_R__UNIQUE_(Init) = GenerateInitInstanceLocal((const vector<short>*)0x0); R__UseDummy(_R__UNIQUE_(Init));

   // Dictionary for non-ClassDef classes
   static void vectorlEshortgR_Dictionary() {
      ::ROOT::GenerateInitInstanceLocal((const vector<short>*)0x0)->GetClass();
   }

} // end of namespace ROOT

namespace ROOT {
   // Wrappers around operator new
   static void *new_vectorlEshortgR(void *p) {
      return  p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<short> : new vector<short>;
   }
   static void *newArray_vectorlEshortgR(Long_t nElements, void *p) {
      return p ? ::new((::ROOT::TOperatorNewHelper*)p) vector<short>[nElements] : new vector<short>[nElements];
   }
   // Wrapper around operator delete
   static void delete_vectorlEshortgR(void *p) {
      delete ((vector<short>*)p);
   }
   static void deleteArray_vectorlEshortgR(void *p) {
      delete [] ((vector<short>*)p);
   }
   static void destruct_vectorlEshortgR(void *p) {
      typedef vector<short> current_t;
      ((current_t*)p)->~current_t();
   }
} // end of namespace ROOT for class vector<short>

/********************************************************
* ./include/Dictionary_DmpEvtFdigiBgo.cc
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************/

#ifdef G__MEMTEST
#undef malloc
#undef free
#endif

#if defined(__GNUC__) && __GNUC__ >= 4 && ((__GNUC_MINOR__ == 2 && __GNUC_PATCHLEVEL__ >= 1) || (__GNUC_MINOR__ >= 3))
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif

extern "C" void G__cpp_reset_tagtableDictionary_DmpEvtFdigiBgo();

extern "C" void G__set_cpp_environmentDictionary_DmpEvtFdigiBgo() {
  G__cpp_reset_tagtableDictionary_DmpEvtFdigiBgo();
}
#include <new>
extern "C" int G__cpp_dllrevDictionary_DmpEvtFdigiBgo() { return(30051515); }

/*********************************************************
* Member function Interface Method
*********************************************************/

/* DmpEvtFdigiBgo */
static int G__Dictionary_DmpEvtFdigiBgo_168_0_1(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmpEvtFdigiBgo* p = NULL;
   char* gvp = (char*) G__getgvp();
   int n = G__getaryconstruct();
   if (n) {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmpEvtFdigiBgo[n];
     } else {
       p = new((void*) gvp) DmpEvtFdigiBgo[n];
     }
   } else {
     if ((gvp == (char*)G__PVOID) || (gvp == 0)) {
       p = new DmpEvtFdigiBgo;
     } else {
       p = new((void*) gvp) DmpEvtFdigiBgo;
     }
   }
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_DmpEvtFdigiBgo));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_2(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtFdigiBgo*) G__getstructoffset())->Reset();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_3(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ((const DmpEvtFdigiBgo*) G__getstructoffset())->nHits());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_4(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ((const DmpEvtFdigiBgo*) G__getstructoffset())->GetBar((short) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_5(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ((const DmpEvtFdigiBgo*) G__getstructoffset())->GetSide((short) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_6(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) ((const DmpEvtFdigiBgo*) G__getstructoffset())->GetLayer((short) G__int(libp->para[0])));
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_7(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 85, (long) DmpEvtFdigiBgo::Class());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_8(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtFdigiBgo::Class_Name());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_9(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 115, (long) DmpEvtFdigiBgo::Class_Version());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_10(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      DmpEvtFdigiBgo::Dictionary();
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_14(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      ((DmpEvtFdigiBgo*) G__getstructoffset())->StreamerNVirtual(*(TBuffer*) libp->para[0].ref);
      G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_15(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtFdigiBgo::DeclFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_16(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmpEvtFdigiBgo::ImplFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_17(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 67, (long) DmpEvtFdigiBgo::ImplFileName());
   return(1 || funcname || hash || result7 || libp) ;
}

static int G__Dictionary_DmpEvtFdigiBgo_168_0_18(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
      G__letint(result7, 105, (long) DmpEvtFdigiBgo::DeclFileLine());
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic copy constructor
static int G__Dictionary_DmpEvtFdigiBgo_168_0_19(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)

{
   DmpEvtFdigiBgo* p;
   void* tmp = (void*) G__int(libp->para[0]);
   p = new DmpEvtFdigiBgo(*(DmpEvtFdigiBgo*) tmp);
   result7->obj.i = (long) p;
   result7->ref = (long) p;
   G__set_tagnum(result7,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_DmpEvtFdigiBgo));
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic destructor
typedef DmpEvtFdigiBgo G__TDmpEvtFdigiBgo;
static int G__Dictionary_DmpEvtFdigiBgo_168_0_20(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   char* gvp = (char*) G__getgvp();
   long soff = G__getstructoffset();
   int n = G__getaryconstruct();
   //
   //has_a_delete: 1
   //has_own_delete1arg: 0
   //has_own_delete2arg: 0
   //
   if (!soff) {
     return(1);
   }
   if (n) {
     if (gvp == (char*)G__PVOID) {
       delete[] (DmpEvtFdigiBgo*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       for (int i = n - 1; i >= 0; --i) {
         ((DmpEvtFdigiBgo*) (soff+(sizeof(DmpEvtFdigiBgo)*i)))->~G__TDmpEvtFdigiBgo();
       }
       G__setgvp((long)gvp);
     }
   } else {
     if (gvp == (char*)G__PVOID) {
       delete (DmpEvtFdigiBgo*) soff;
     } else {
       G__setgvp((long) G__PVOID);
       ((DmpEvtFdigiBgo*) (soff))->~G__TDmpEvtFdigiBgo();
       G__setgvp((long)gvp);
     }
   }
   G__setnull(result7);
   return(1 || funcname || hash || result7 || libp) ;
}

// automatic assignment operator
static int G__Dictionary_DmpEvtFdigiBgo_168_0_21(G__value* result7, G__CONST char* funcname, struct G__param* libp, int hash)
{
   DmpEvtFdigiBgo* dest = (DmpEvtFdigiBgo*) G__getstructoffset();
   *dest = *(DmpEvtFdigiBgo*) libp->para[0].ref;
   const DmpEvtFdigiBgo& obj = *dest;
   result7->ref = (long) (&obj);
   result7->obj.i = (long) (&obj);
   return(1 || funcname || hash || result7 || libp) ;
}


/* Setting up global function */

/*********************************************************
* Member function Stub
*********************************************************/

/* DmpEvtFdigiBgo */

/*********************************************************
* Global function Stub
*********************************************************/

/*********************************************************
* Get size of pointer to member function
*********************************************************/
class G__Sizep2memfuncDictionary_DmpEvtFdigiBgo {
 public:
  G__Sizep2memfuncDictionary_DmpEvtFdigiBgo(): p(&G__Sizep2memfuncDictionary_DmpEvtFdigiBgo::sizep2memfunc) {}
    size_t sizep2memfunc() { return(sizeof(p)); }
  private:
    size_t (G__Sizep2memfuncDictionary_DmpEvtFdigiBgo::*p)();
};

size_t G__get_sizep2memfuncDictionary_DmpEvtFdigiBgo()
{
  G__Sizep2memfuncDictionary_DmpEvtFdigiBgo a;
  G__setsizep2memfunc((int)a.sizep2memfunc());
  return((size_t)a.sizep2memfunc());
}


/*********************************************************
* virtual base class offset calculation interface
*********************************************************/

   /* Setting up class inheritance */

/*********************************************************
* Inheritance information setup/
*********************************************************/
extern "C" void G__cpp_setup_inheritanceDictionary_DmpEvtFdigiBgo() {

   /* Setting up class inheritance */
   if(0==G__getnumbaseclass(G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_DmpEvtFdigiBgo))) {
     DmpEvtFdigiBgo *G__Lderived;
     G__Lderived=(DmpEvtFdigiBgo*)0x1000;
     {
       TObject *G__Lpbase=(TObject*)G__Lderived;
       G__inheritance_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_DmpEvtFdigiBgo),G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_TObject),(long)G__Lpbase-(long)G__Lderived,1,1);
     }
   }
}

/*********************************************************
* typedef information setup/
*********************************************************/
extern "C" void G__cpp_setup_typetableDictionary_DmpEvtFdigiBgo() {

   /* Setting up typedef entry */
   G__search_typename2("Version_t",115,-1,0,-1);
   G__setnewtype(-1,"Class version identifier (short)",0);
   G__search_typename2("vector<ROOT::TSchemaHelper>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("vector<TVirtualArray*>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR),0,-1);
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<const_iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
   G__search_typename2("reverse_iterator<iterator>",117,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR),0,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR));
   G__setnewtype(-1,NULL,0);
}

/*********************************************************
* Data Member information setup/
*********************************************************/

   /* Setting up class,struct,union tag member variable */

   /* DmpEvtFdigiBgo */
static void G__setup_memvarDmpEvtFdigiBgo(void) {
   G__tag_memvar_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_DmpEvtFdigiBgo));
   { DmpEvtFdigiBgo *p; p=(DmpEvtFdigiBgo*)0x1000; if (p) { }
   G__memvar_setup((void*)((long)(&p->fGlobalPmtID)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_vectorlEshortcOallocatorlEshortgRsPgR),G__defined_typename("vector<short>"),-1,1,"fGlobalPmtID=",0,"unique sensitive detector(minimum detector unit) ID.Pmt End of Bgo bar. fGlobalPmtID =  (layer*2+side)*22+bar;");
   G__memvar_setup((void*)((long)(&p->fADC)-(long)(p)),117,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_vectorlEshortcOallocatorlEshortgRsPgR),G__defined_typename("vector<short>"),-1,1,"fADC=",0,"unit ADC");
   G__memvar_setup((void*)0,85,0,0,G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_TClass),-1,-2,4,"fgIsA=",0,(char*)NULL);
   }
   G__tag_memvar_reset();
}

extern "C" void G__cpp_setup_memvarDictionary_DmpEvtFdigiBgo() {
}
/***********************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
************************************************************
***********************************************************/

/*********************************************************
* Member function information setup for each class
*********************************************************/
static void G__setup_memfuncDmpEvtFdigiBgo(void) {
   /* DmpEvtFdigiBgo */
   G__tag_memfunc_setup(G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_DmpEvtFdigiBgo));
   G__memfunc_setup("DmpEvtFdigiBgo",1355,G__Dictionary_DmpEvtFdigiBgo_168_0_1, 105, G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_DmpEvtFdigiBgo), -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Reset",515,G__Dictionary_DmpEvtFdigiBgo_168_0_2, 121, -1, -1, 0, 0, 1, 1, 0, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("nHits",518,G__Dictionary_DmpEvtFdigiBgo_168_0_3, 115, -1, -1, 0, 0, 1, 1, 9, "", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetBar",565,G__Dictionary_DmpEvtFdigiBgo_168_0_4, 115, -1, -1, 0, 1, 1, 1, 9, "s - - 0 - Gpmt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetSide",677,G__Dictionary_DmpEvtFdigiBgo_168_0_5, 115, -1, -1, 0, 1, 1, 1, 9, "s - - 0 - Gpmt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("GetLayer",797,G__Dictionary_DmpEvtFdigiBgo_168_0_6, 115, -1, -1, 0, 1, 1, 1, 9, "s - - 0 - Gpmt", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("Class",502,G__Dictionary_DmpEvtFdigiBgo_168_0_7, 85, G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_TClass), -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (TClass* (*)())(&DmpEvtFdigiBgo::Class) ), 0);
   G__memfunc_setup("Class_Name",982,G__Dictionary_DmpEvtFdigiBgo_168_0_8, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtFdigiBgo::Class_Name) ), 0);
   G__memfunc_setup("Class_Version",1339,G__Dictionary_DmpEvtFdigiBgo_168_0_9, 115, -1, G__defined_typename("Version_t"), 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (Version_t (*)())(&DmpEvtFdigiBgo::Class_Version) ), 0);
   G__memfunc_setup("Dictionary",1046,G__Dictionary_DmpEvtFdigiBgo_168_0_10, 121, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (void (*)())(&DmpEvtFdigiBgo::Dictionary) ), 0);
   G__memfunc_setup("IsA",253,(G__InterfaceMethod) NULL,85, G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_TClass), -1, 0, 0, 1, 1, 8, "", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("ShowMembers",1132,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TMemberInspector' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("Streamer",835,(G__InterfaceMethod) NULL,121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - -", (char*)NULL, (void*) NULL, 1);
   G__memfunc_setup("StreamerNVirtual",1656,G__Dictionary_DmpEvtFdigiBgo_168_0_14, 121, -1, -1, 0, 1, 1, 1, 0, "u 'TBuffer' - 1 - ClassDef_StreamerNVirtual_b", (char*)NULL, (void*) NULL, 0);
   G__memfunc_setup("DeclFileName",1145,G__Dictionary_DmpEvtFdigiBgo_168_0_15, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtFdigiBgo::DeclFileName) ), 0);
   G__memfunc_setup("ImplFileLine",1178,G__Dictionary_DmpEvtFdigiBgo_168_0_16, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmpEvtFdigiBgo::ImplFileLine) ), 0);
   G__memfunc_setup("ImplFileName",1171,G__Dictionary_DmpEvtFdigiBgo_168_0_17, 67, -1, -1, 0, 0, 3, 1, 1, "", (char*)NULL, (void*) G__func2void( (const char* (*)())(&DmpEvtFdigiBgo::ImplFileName) ), 0);
   G__memfunc_setup("DeclFileLine",1152,G__Dictionary_DmpEvtFdigiBgo_168_0_18, 105, -1, -1, 0, 0, 3, 1, 0, "", (char*)NULL, (void*) G__func2void( (int (*)())(&DmpEvtFdigiBgo::DeclFileLine) ), 0);
   // automatic copy constructor
   G__memfunc_setup("DmpEvtFdigiBgo", 1355, G__Dictionary_DmpEvtFdigiBgo_168_0_19, (int) ('i'), G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_DmpEvtFdigiBgo), -1, 0, 1, 1, 1, 0, "u 'DmpEvtFdigiBgo' - 11 - -", (char*) NULL, (void*) NULL, 0);
   // automatic destructor
   G__memfunc_setup("~DmpEvtFdigiBgo", 1481, G__Dictionary_DmpEvtFdigiBgo_168_0_20, (int) ('y'), -1, -1, 0, 0, 1, 1, 0, "", (char*) NULL, (void*) NULL, 1);
   // automatic assignment operator
   G__memfunc_setup("operator=", 937, G__Dictionary_DmpEvtFdigiBgo_168_0_21, (int) ('u'), G__get_linked_tagnum(&G__Dictionary_DmpEvtFdigiBgoLN_DmpEvtFdigiBgo), -1, 1, 1, 1, 1, 0, "u 'DmpEvtFdigiBgo' - 11 - -", (char*) NULL, (void*) NULL, 0);
   G__tag_memfunc_reset();
}


/*********************************************************
* Member function information setup
*********************************************************/
extern "C" void G__cpp_setup_memfuncDictionary_DmpEvtFdigiBgo() {
}

/*********************************************************
* Global variable information setup for each class
*********************************************************/
static void G__cpp_setup_global0() {

   /* Setting up global variables */
   G__resetplocal();

}

static void G__cpp_setup_global1() {

   G__resetglobalenv();
}
extern "C" void G__cpp_setup_globalDictionary_DmpEvtFdigiBgo() {
  G__cpp_setup_global0();
  G__cpp_setup_global1();
}

/*********************************************************
* Global function information setup for each class
*********************************************************/
static void G__cpp_setup_func0() {
   G__lastifuncposition();

}

static void G__cpp_setup_func1() {
}

static void G__cpp_setup_func2() {
}

static void G__cpp_setup_func3() {
}

static void G__cpp_setup_func4() {
}

static void G__cpp_setup_func5() {
}

static void G__cpp_setup_func6() {
}

static void G__cpp_setup_func7() {
}

static void G__cpp_setup_func8() {
}

static void G__cpp_setup_func9() {
}

static void G__cpp_setup_func10() {
}

static void G__cpp_setup_func11() {
}

static void G__cpp_setup_func12() {

   G__resetifuncposition();
}

extern "C" void G__cpp_setup_funcDictionary_DmpEvtFdigiBgo() {
  G__cpp_setup_func0();
  G__cpp_setup_func1();
  G__cpp_setup_func2();
  G__cpp_setup_func3();
  G__cpp_setup_func4();
  G__cpp_setup_func5();
  G__cpp_setup_func6();
  G__cpp_setup_func7();
  G__cpp_setup_func8();
  G__cpp_setup_func9();
  G__cpp_setup_func10();
  G__cpp_setup_func11();
  G__cpp_setup_func12();
}

/*********************************************************
* Class,struct,union,enum tag information setup
*********************************************************/
/* Setup class/struct taginfo */
G__linked_taginfo G__Dictionary_DmpEvtFdigiBgoLN_TClass = { "TClass" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtFdigiBgoLN_TBuffer = { "TBuffer" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtFdigiBgoLN_TMemberInspector = { "TMemberInspector" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtFdigiBgoLN_TObject = { "TObject" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtFdigiBgoLN_vectorlEshortcOallocatorlEshortgRsPgR = { "vector<short,allocator<short> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtFdigiBgoLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR = { "vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtFdigiBgoLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR = { "reverse_iterator<vector<ROOT::TSchemaHelper,allocator<ROOT::TSchemaHelper> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtFdigiBgoLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR = { "vector<TVirtualArray*,allocator<TVirtualArray*> >" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtFdigiBgoLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR = { "reverse_iterator<vector<TVirtualArray*,allocator<TVirtualArray*> >::iterator>" , 99 , -1 };
G__linked_taginfo G__Dictionary_DmpEvtFdigiBgoLN_DmpEvtFdigiBgo = { "DmpEvtFdigiBgo" , 99 , -1 };

/* Reset class/struct taginfo */
extern "C" void G__cpp_reset_tagtableDictionary_DmpEvtFdigiBgo() {
  G__Dictionary_DmpEvtFdigiBgoLN_TClass.tagnum = -1 ;
  G__Dictionary_DmpEvtFdigiBgoLN_TBuffer.tagnum = -1 ;
  G__Dictionary_DmpEvtFdigiBgoLN_TMemberInspector.tagnum = -1 ;
  G__Dictionary_DmpEvtFdigiBgoLN_TObject.tagnum = -1 ;
  G__Dictionary_DmpEvtFdigiBgoLN_vectorlEshortcOallocatorlEshortgRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtFdigiBgoLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtFdigiBgoLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dictionary_DmpEvtFdigiBgoLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR.tagnum = -1 ;
  G__Dictionary_DmpEvtFdigiBgoLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR.tagnum = -1 ;
  G__Dictionary_DmpEvtFdigiBgoLN_DmpEvtFdigiBgo.tagnum = -1 ;
}


extern "C" void G__cpp_setup_tagtableDictionary_DmpEvtFdigiBgo() {

   /* Setting up class,struct,union tag entry */
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtFdigiBgoLN_TClass);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtFdigiBgoLN_TBuffer);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtFdigiBgoLN_TMemberInspector);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtFdigiBgoLN_TObject);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtFdigiBgoLN_vectorlEshortcOallocatorlEshortgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtFdigiBgoLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtFdigiBgoLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtFdigiBgoLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR);
   G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtFdigiBgoLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR);
   G__tagtable_setup(G__get_linked_tagnum_fwd(&G__Dictionary_DmpEvtFdigiBgoLN_DmpEvtFdigiBgo),sizeof(DmpEvtFdigiBgo),-1,292096,(char*)NULL,G__setup_memvarDmpEvtFdigiBgo,G__setup_memfuncDmpEvtFdigiBgo);
}
extern "C" void G__cpp_setupDictionary_DmpEvtFdigiBgo(void) {
  G__check_setup_version(30051515,"G__cpp_setupDictionary_DmpEvtFdigiBgo()");
  G__set_cpp_environmentDictionary_DmpEvtFdigiBgo();
  G__cpp_setup_tagtableDictionary_DmpEvtFdigiBgo();

  G__cpp_setup_inheritanceDictionary_DmpEvtFdigiBgo();

  G__cpp_setup_typetableDictionary_DmpEvtFdigiBgo();

  G__cpp_setup_memvarDictionary_DmpEvtFdigiBgo();

  G__cpp_setup_memfuncDictionary_DmpEvtFdigiBgo();
  G__cpp_setup_globalDictionary_DmpEvtFdigiBgo();
  G__cpp_setup_funcDictionary_DmpEvtFdigiBgo();

   if(0==G__getsizep2memfunc()) G__get_sizep2memfuncDictionary_DmpEvtFdigiBgo();
  return;
}
class G__cpp_setup_initDictionary_DmpEvtFdigiBgo {
  public:
    G__cpp_setup_initDictionary_DmpEvtFdigiBgo() { G__add_setup_func("Dictionary_DmpEvtFdigiBgo",(G__incsetup)(&G__cpp_setupDictionary_DmpEvtFdigiBgo)); G__call_setup_funcs(); }
   ~G__cpp_setup_initDictionary_DmpEvtFdigiBgo() { G__remove_setup_func("Dictionary_DmpEvtFdigiBgo"); }
};
G__cpp_setup_initDictionary_DmpEvtFdigiBgo G__cpp_setup_initializerDictionary_DmpEvtFdigiBgo;

